export default {
  lineColor: '颜色',
  lineColorFull: 'Line color',
  fillColor: '填充色',
  fillColorFull: 'Fill color',
  alpha: '透明度',
  alphaFull: 'Alpha',
  lineWidth: '线宽',
  lineWidthFull: 'Line width',
  arrowLength: '箭头大小',
  arrowLengthFull: 'Arrow length',
  eraserWidth: '大小',
  eraserWidthFull: 'Eraser width',
  textColor: '颜色',
  textColorFull: 'Text color',
  fontSize: '字号',
  fontSizeFull: 'Font size',
  fontStrokeSize: 'St',
  fontStrokeSizeFull: 'Stroke width',
  fontStyle: '样式',
  fontStyleFull: 'Font style',
  fontName: '字体',
  fontNameFull: 'Font name',
  textStrokeColor: '颜色',
  textStrokeColorFull: 'Stroke color',
  apply: '应用',
  cancel: '取消',
  close: '关闭',
  clear: '清除',
  width: '宽',
  height: '高',
  keepRatio: '固定宽高比',
  fillPageWith: '设置背景颜色',
  pixelSize: '像素大小',
  pixelSizeFull: 'Pixel size',
  resizeScale: 'Scale',
  resizeResize: 'Resize',
  backgroundColor: '背景颜色',
  pixelizePixelSize: 'Pixelize pixel size',
  language: '语言',
  wrongPixelSizeValue:
    'Wrong pixel size. You can enter e.g. \'20%\' which mean pixel size will be 1/5 of ' +
    'the selected area side, or \'4\' means 4 px',
  tools: {
    crop: '剪裁',
    pixelize: '马赛克',
    rect: '矩形',
    ellipse: '椭圆',
    line: '直线',
    arrow: '箭头',
    rotate: '旋转画布',
    save: '保存图片',
    load: '读取图片',
    text: '文字',
    brush: '画笔',
    resize: '缩放',
    open: '打开图片',
    select: '选择',
    close: '关闭',
    eraser: '橡皮擦',
    settings: '设置',
    undo: '撤销',
    redo: '重复',
  },
  pasteOptions: {
    fit: 'Replace all',
    extend_down: 'Extend down',
    extend_right: 'Extend right',
    over: 'Paste over',
    how_to_paste: 'How to paste?',
  },
};
